//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanningSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course_Account
    {
        public int userId { get; set; }
        public int courseId { get; set; }
    
        public virtual Course_Account Course_Account1 { get; set; }
        public virtual Course_Account Course_Account2 { get; set; }
    }
}
