//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanningSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unavailability
    {
        public int UnavailabilityID { get; set; }
        public System.DateTime UnavailabilityStartTime { get; set; }
        public System.DateTime UnavailabilityEndTime { get; set; }
        public string UnavailabilityCause { get; set; }
        public int userID { get; set; }
    }
}
